baseURL = 'https://tinydev.blog/'
languageCode = 'en-us'
title = 'Tiny Dev Blog'
# theme = 'triple-hyde'
theme ="hyde-hyde"
# copyright="© Stan Korolev"
# googleAnalytics = ""
# enableEmoji=true
# enableRobotsTXT=true
# pygmentsUseClasses=true
# pygmentsCodeFences=true


## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

summarylength = 123

#paginate = 5

## Site Settings


[params]
# author = "Author"
# title = "Title"
  description = "101, my name is Stan Korolev, Ph.D Software Developer in Vancouver, BC"
    # sub = "I'm a Web Developer and Entrepreneur"
  mainSections = ["posts"]

    # Hyde theme specific setting
#  themeColor = "theme-base-0d"

[params.social]
linkedin = "korolevst"
instagram= "knoxwelle"
gravatar = "korolevst@gmail.com"
# twitter = "htr3n"
# keybase = "htr3n"
# github = "htr3n"

[taxonomies]
   tag = "tags"
   category = "categories"


## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Categories"
    weight = 300
    identifier = "categories"
    url = "/categories/"
[[menu.main]]
    name = "Tags"
    weight = 400
    identifier = "tags"
    url = "/tags/"
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 500
    url = "/resume/resume"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 600
    url = "/about/about"
